services:

  pygeoapi_cite:
    image: geopython/pygeoapi_covid-19:latest

    build: ./pygeoapi

    container_name: pygeoapi_covid-19

    restart: unless-stopped

    expose:
      - "80"

#    ports:
#      - "5000:80"

    environment:
     - SCRIPT_NAME=/covid-19

    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:demo.pygeoapi.io,localhost;PathPrefix:/covid-19"
      - "traefik.backend=pygeoapi_covid-19"
      - "traefik.frontend.priority=100"
      - "traefik.docker.network=pygeoapi-network"

networks:
  pygeoapi-network:
    external: true
